version: '2.2'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - 3000:3000

  sqlite:
    image: nouchka/sqlite3:latest
    volumes:
      - ./database:/var/lib/sqlite/data
    ports:
      - 5432:5432